name: GitHub MSYS2
on: [push]

jobs:
  windows_wheels:
    name: Build dependencies for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          # location: D:\
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-cc patch m4 lzip wget tar make diffutils unzip
      - name: Build Dependencies
        run: bin/cibw_before_build_windows.sh
